---
title: "MSDS of the Laboratories of the Faculty of Agricultural, Environmental and Food Sciences"
---

::: {style="font-size:18px;"}

The Material Safety Data Sheets (MSDS) of the laboratories of the Faculty of Agricultural, Environmental and Food Sciences of the Free University of Bozen/Bolzano can be found on this page. The lists are sorted alphabetically and by individual laboratory. The MSDSs are constantly updated by the reagent manufacturer.
The date on which the lists were updated can be found on each individual page.

:::

::: {style="font-size:20px;"}

# Main Building

----

## E Building

- [BZ-E0.10](BZ_E010.qmd) - Technical Room
- [BZ-E0.11](BZ_E011.qmd) - Laboratory for Agro-Environmental Science
- BZ-E0.12a - Laboratory for Instrumental Analyses
- [BZ-E0.12b](BZ_E012b.qmd) - Lab for Plant and Microbe Biotechnologies
- [BZ-E0.20](BZ_E020.qmd) - Laboratory for Sample Preparation
- [BZ-E0.21](BZ_E021.qmd) - Laboratory for Bioorganic Chemistry and Bio-crystallography
- [BZ-E0.22](BZ_E022.qmd) - Laboratory for Phytopathology
- [BZ-E0.23](BZ_E023.qmd) - Laboratory for Animal Science
- [BZ-E1.10](BZ_E110.qmd) - Laboratory for Soil DNA
- [BZ-E1.11](BZ_E111.qmd) - Isotope Laboratory
- [BZ-E1.12](BZ_E112.qmd) - Teaching Laboratory I
- [BZ-E1.20](BZ_E120.qmd) - Laboratory for Analytical Chemistry
- [BZ-E1.21](BZ_E121.qmd) - Soil molecular ecology lab
- [BZ-E1.22](BZ_E122.qmd) - Molecular entomology lab
- [BZ-E1.23](BZ_E123.qmd) - Laboratory for Soil Analysis
- [BZ-E2.11](BZ_E211.qmd) - Laboratory for Insect Ecology & Sustainable Pest Management
- [BZ-E2.31](BZ_E231.qmd) - Teaching Laboratory II

## K Building

- BZ-KU.03 - Climatic chamber
- BZ-KU.06 - Room for Sample Preparation

# NOI Techpark

----

## A2 Building

- BZ-NOI-A2 2.03 - Bakery Inspirience Center
- BZ-NOI-A2 2.05 - Dairy Center
- BZ-NOI-A2 2.07 - Vegetable Fermentation
- BZ-NOI-A2 2.13 - Food Physics Lab
- [BZ-NOI-A2 2.15](BZ_A2215.qmd) - Technicians Office
- [BZ-NOI-A2 2.25](BZ_A2225.qmd) - Advanced Technologies Lab
- [BZ-NOI-A2 2.26](BZ_A2226.qmd) - Food Chemistry Lab
- [BZ-NOI-A2 2.27](BZ_A2227.qmd) - Phenomics & Metabolomics
- [BZ-NOI-A2 2.28](BZ_A2228.qmd) - Basic Microbiology
- [BZ-NOI-A2 2.29](BZ_A2229.qmd) - Genetics & SHIME
- [BZ-NOI-A2 2.38](BZ_A2238.qmd) - Twinshime
- [BZ-NOI-A2.3.03c](BZ_A2303c.qmd) - Oenolab
- [BZ-NOI-A2 3.03e](BZ_A2303e.qmd) - Microscopy
- [BZ-NOI-A2 3.03f](BZ_A2303f.qmd) - Proteomics
- [BZ-NOI-A2.4.09](BZ_A2409.qmd) - Laboratory for Bioenergy & Biofuels - Analytics and Processes

## B5 Building

- BZ-NOI-B5 0.02 - Agroforestry Innovations Lab

## D2 Building

- [BZ-NOI-D2 2](BZ-NOI-D2 2.qmd) - International Competence Centre on Food Fermentations

## F1 Building

- [BZ-NOI-F1 2.26](BZ_F1226.qmd) - Chemical Teaching Lab
- [BZ-NOI-F1 2.29](BZ_F1229.qmd) - Applied and Agro-Environmental Microbiology Lab

# Laimburg

----

- Laimburg 1 - Laboratory for Soil and Plant processing
- Laimburg 2 - Laboratory for Animal Science 
- Laimburg Lab 1 (D.0.08) - Laboratory for Plant Pathology and Plant Biology
- Laimburg Lab 2 (D.0.07) - Laboratory for Analitical Chemistry
- Laimburg Lab 3 (D.0.09) - Laboratory for Ecophysiology
- [Laimburg-Serra](Laimburg_Serra.qmd) - Greenhouse Laimburg

:::